name: Proxy Speed Test and Update

on:
  schedule:
    - cron: "*/5 * * * *" # Run every 5 mins
  workflow_dispatch:

concurrency:
  group: test-and-update-proxies

jobs:
  proxy-test-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml markdown

      - name: Update Proxy List
        run: |
          git clone https://github.com/zloi-user/hideip.me.git temp-proxy-source
          cp temp-proxy-source/*.txt ./
          rm -rf temp-proxy-source

      - name: Test Proxies and Generate Report
        run: |
          python test_proxies.py

      - name: Commit and Push Updates
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add proxy_report.md
          git commit -m "Update proxy report"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
